<form action="/posts" method="post">


  <div>
        <label>
            Name
            <input type="text" name="post[name]"
                value="<?= $post['name'] ?>"
            >
        </label>
        <div class="error">
            <?php
                if (array_key_exists('name', $errors )): ?>
                    <span><?=  $errors['name']   ?></span>
            <?php endif;?>
        </div>
    </div>


    <div>
        <label>
            Body
            <input type="text" name="post[body]"
                   value="<?= $post['body'] ?>"
            >

        </label>
        <div class="error">
          <?php if (array_key_exists('body', $errors )): ?>
                <span><?= $errors['body'] ?? ''?></span>
            <?php endif;?>
        </div>
    </div>

    <input type="submit" value="Сохранить">


</form>

<style>
    .error {
        color:red;
        padding:5px 5px 15px 5px;
    }
</style>

