<html>
<head>
    <link rel="stylesheet" href="/css/main.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<div class="top-menu">
    New menu
</div>
<div class="main">
    <div class="side-bar" >
        SITE BAR
    </div>
    <div class="content">
        <div class="flex-conteiner">
            <div class="card">1</div>
            <div class="card">2</div>
            <div class="card">3</div>
        </div>
    </div>
</div>
<div class="footer">
    Футер
</div>
 
</body>
</html>


