<html>
<head>
    <link rel="stylesheet" href="/css/main.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

<section class="grid-12">
    <div class="grid-header bg-gray">1</div>
    <div class="grid-aside bg-red">2</div>
    <div class="grid-content bg-blue">header-top — Самая верхняя линия, от которой отрисовывается шапка сайта.
        content-begin — Линия, откуда начинается основной контент сайта. В данном случае aside и main. Используем её как ограничитель высоты шапки.
       ляет переносить строки внутри свойства. Таким образом свойство grid-template-areas становится более наглядным. Также внутри самих значений можно проставлять любое количество пробелов. Колонки в каждой строке можно выставить друг под другом:</div>
    <div class="grid-right bg-red">4</div>
    <div class="grid-footer bg-green">5</div>
</section>

</body>
</html>


