<a href="/courses">Курсы</a>

<?php if (count($flash) > 0): ?>
    <ul>
        <?php foreach ($flash as $messages): ?>
            <?php foreach ($messages as $message): ?>
                <li><?= $message ?></li>
            <?php endforeach ?>
        <?php endforeach ?>
    </ul>
<?php endif ?>

<?php if (isset($validated['name'])) {?>
 <div><strong>Имя </strong>: <?= $validated['name'];?></div>
<form action="session" method="POST">
    <input type="hidden" name="_METHOD" value="DELETE">
    <input type="submit" value="Sign Out">
</form>

<?php } else { ?>
    <form action="session" method="POST">
        <div>
            <div>
            <label>
                Name
                <input type="text" name="user[name]"
                       value="<?= $user['name'] ?>"
                >
            </label>
            </div>
            <div>
            <label>
                Password
                <input type="text" name=user[password]"
                       value="<?= $user['password'] ?>"
                >
            </label>
            </div>
        </div>
        <input type="submit" value="Sign In">
    </form>
<?php }?>
 