<?php  if ( count($messages) > 0) : ?>
    <div class="<?= array_keys($messages)[0]?>" > <?=  $messages[array_keys($messages)[0]][0]?> </div>
<?php endif;?>

<table>
    <thead>
    <tr><td>id</td><td>Заголовок</td><td>Оплата</td></tr>
    </thead>
    <?php foreach ($courses as $course): ?>
    <tr>

        <td><a href="/courses/<?= $course['id']?>"><?= $course['title']?></a></td>
        <td><?= $course['paid']?></td>
    </tr>
    <?php endforeach; ?>
</table>
<br>
 
<a href="/courses/new">Создать новую запись</a>

<style>
    .success {
        color:green;
        font-size:1.5em;
    }
    .error {
        color:red;
        font-size:1.5em;
    }
</style>